from __future__ import annotations

import re
import unicodedata
from collections.abc import Mapping


def _country_key(value: object) -> str:
    text = unicodedata.normalize("NFKD", str(value or "").casefold())
    text = "".join(character for character in text if not unicodedata.combining(character))
    text = re.sub(r"[^\w]+", " ", text, flags=re.UNICODE).replace("_", " ")
    return re.sub(r"\s+", " ", text).strip()


COUNTRY_NAME_TO_ALPHA2: dict[str, str] = {
    _country_key(name): code
    for code, names in {
        "ad": ("Andorra",),
        "ae": ("United Arab Emirates", "UAE"),
        "af": ("Afghanistan",),
        "ag": ("Antigua and Barbuda",),
        "ai": ("Anguilla",),
        "al": ("Albania",),
        "am": ("Armenia",),
        "ao": ("Angola",),
        "aq": ("Antarctica",),
        "ar": ("Argentina",),
        "as": ("American Samoa",),
        "at": ("Austria",),
        "au": ("Australia",),
        "aw": ("Aruba",),
        "ax": ("Aland Islands",),
        "az": ("Azerbaijan",),
        "ba": ("Bosnia and Herzegovina", "Bosnia"),
        "bb": ("Barbados",),
        "bd": ("Bangladesh",),
        "be": ("Belgium",),
        "bf": ("Burkina Faso",),
        "bg": ("Bulgaria",),
        "bh": ("Bahrain",),
        "bi": ("Burundi",),
        "bj": ("Benin",),
        "bl": ("Saint Barthelemy", "St Barthelemy"),
        "bm": ("Bermuda",),
        "bn": ("Brunei Darussalam", "Brunei"),
        "bo": ("Bolivia", "Bolivia Plurinational State of"),
        "bq": ("Bonaire Sint Eustatius and Saba", "Caribbean Netherlands"),
        "br": ("Brazil",),
        "bs": ("Bahamas",),
        "bt": ("Bhutan",),
        "bv": ("Bouvet Island",),
        "bw": ("Botswana",),
        "by": ("Belarus",),
        "bz": ("Belize",),
        "ca": ("Canada",),
        "cc": ("Cocos Keeling Islands",),
        "cd": ("Congo Democratic Republic of the", "DR Congo", "Democratic Republic of Congo"),
        "cf": ("Central African Republic",),
        "cg": ("Congo", "Republic of the Congo"),
        "ch": ("Switzerland", "Swiss Confederation"),
        "ci": ("Cote d Ivoire", "Ivory Coast"),
        "ck": ("Cook Islands",),
        "cl": ("Chile",),
        "cm": ("Cameroon",),
        "cn": ("China",),
        "co": ("Colombia",),
        "cr": ("Costa Rica",),
        "cu": ("Cuba",),
        "cv": ("Cabo Verde", "Cape Verde"),
        "cw": ("Curacao",),
        "cx": ("Christmas Island",),
        "cy": ("Cyprus",),
        "cz": ("Czechia", "Czech Republic"),
        "de": ("Germany",),
        "dj": ("Djibouti",),
        "dk": ("Denmark",),
        "dm": ("Dominica",),
        "do": ("Dominican Republic",),
        "dz": ("Algeria",),
        "ec": ("Ecuador",),
        "ee": ("Estonia",),
        "eg": ("Egypt",),
        "eh": ("Western Sahara",),
        "er": ("Eritrea",),
        "es": ("Spain",),
        "et": ("Ethiopia",),
        "fi": ("Finland",),
        "fj": ("Fiji",),
        "fk": ("Falkland Islands", "Malvinas"),
        "fm": ("Micronesia", "Micronesia Federated States of"),
        "fo": ("Faroe Islands",),
        "fr": ("France",),
        "ga": ("Gabon",),
        "gb": ("United Kingdom", "UK", "Great Britain", "Britain"),
        "gd": ("Grenada",),
        "ge": ("Georgia",),
        "gf": ("French Guiana",),
        "gg": ("Guernsey",),
        "gh": ("Ghana",),
        "gi": ("Gibraltar",),
        "gl": ("Greenland",),
        "gm": ("Gambia",),
        "gn": ("Guinea",),
        "gp": ("Guadeloupe",),
        "gq": ("Equatorial Guinea",),
        "gr": ("Greece",),
        "gs": ("South Georgia and the South Sandwich Islands",),
        "gt": ("Guatemala",),
        "gu": ("Guam",),
        "gw": ("Guinea Bissau",),
        "gy": ("Guyana",),
        "hk": ("Hong Kong",),
        "hm": ("Heard Island and McDonald Islands",),
        "hn": ("Honduras",),
        "hr": ("Croatia",),
        "ht": ("Haiti",),
        "hu": ("Hungary",),
        "id": ("Indonesia",),
        "ie": ("Ireland",),
        "il": ("Israel",),
        "im": ("Isle of Man",),
        "in": ("India",),
        "io": ("British Indian Ocean Territory",),
        "iq": ("Iraq",),
        "ir": ("Iran", "Iran Islamic Republic of"),
        "is": ("Iceland",),
        "it": ("Italy",),
        "je": ("Jersey",),
        "jm": ("Jamaica",),
        "jo": ("Jordan",),
        "jp": ("Japan",),
        "ke": ("Kenya",),
        "kg": ("Kyrgyzstan",),
        "kh": ("Cambodia",),
        "ki": ("Kiribati",),
        "km": ("Comoros",),
        "kn": ("Saint Kitts and Nevis", "St Kitts and Nevis"),
        "kp": ("North Korea", "Korea Democratic People s Republic of"),
        "kr": ("South Korea", "Korea Republic of"),
        "kw": ("Kuwait",),
        "ky": ("Cayman Islands",),
        "kz": ("Kazakhstan",),
        "la": ("Laos", "Lao People s Democratic Republic"),
        "lb": ("Lebanon",),
        "lc": ("Saint Lucia", "St Lucia"),
        "li": ("Liechtenstein",),
        "lk": ("Sri Lanka",),
        "lr": ("Liberia",),
        "ls": ("Lesotho",),
        "lt": ("Lithuania",),
        "lu": ("Luxembourg",),
        "lv": ("Latvia",),
        "ly": ("Libya",),
        "ma": ("Morocco",),
        "mc": ("Monaco",),
        "md": ("Moldova", "Moldova Republic of"),
        "me": ("Montenegro",),
        "mf": ("Saint Martin", "St Martin"),
        "mg": ("Madagascar",),
        "mh": ("Marshall Islands",),
        "mk": ("North Macedonia", "Macedonia"),
        "ml": ("Mali",),
        "mm": ("Myanmar", "Burma"),
        "mn": ("Mongolia",),
        "mo": ("Macao", "Macau"),
        "mp": ("Northern Mariana Islands",),
        "mq": ("Martinique",),
        "mr": ("Mauritania",),
        "ms": ("Montserrat",),
        "mt": ("Malta",),
        "mu": ("Mauritius",),
        "mv": ("Maldives",),
        "mw": ("Malawi",),
        "mx": ("Mexico",),
        "my": ("Malaysia",),
        "mz": ("Mozambique",),
        "na": ("Namibia",),
        "nc": ("New Caledonia",),
        "ne": ("Niger",),
        "nf": ("Norfolk Island",),
        "ng": ("Nigeria",),
        "ni": ("Nicaragua",),
        "nl": ("Netherlands", "Nederland"),
        "no": ("Norway",),
        "np": ("Nepal",),
        "nr": ("Nauru",),
        "nu": ("Niue",),
        "nz": ("New Zealand",),
        "om": ("Oman",),
        "pa": ("Panama",),
        "pe": ("Peru",),
        "pf": ("French Polynesia",),
        "pg": ("Papua New Guinea",),
        "ph": ("Philippines", "Republic of the Philippines"),
        "pk": ("Pakistan",),
        "pl": ("Poland",),
        "pm": ("Saint Pierre and Miquelon", "St Pierre and Miquelon"),
        "pn": ("Pitcairn",),
        "pr": ("Puerto Rico",),
        "ps": ("Palestine", "State of Palestine"),
        "pt": ("Portugal",),
        "pw": ("Palau",),
        "py": ("Paraguay",),
        "qa": ("Qatar",),
        "re": ("Reunion",),
        "ro": ("Romania",),
        "rs": ("Serbia",),
        "ru": ("Russia", "Russian Federation"),
        "rw": ("Rwanda",),
        "sa": ("Saudi Arabia",),
        "sb": ("Solomon Islands",),
        "sc": ("Seychelles",),
        "sd": ("Sudan",),
        "se": ("Sweden",),
        "sg": ("Singapore",),
        "sh": ("Saint Helena Ascension and Tristan da Cunha", "St Helena"),
        "si": ("Slovenia",),
        "sj": ("Svalbard and Jan Mayen",),
        "sk": ("Slovakia",),
        "sl": ("Sierra Leone",),
        "sm": ("San Marino",),
        "sn": ("Senegal",),
        "so": ("Somalia",),
        "sr": ("Suriname",),
        "ss": ("South Sudan",),
        "st": ("Sao Tome and Principe",),
        "sv": ("El Salvador",),
        "sx": ("Sint Maarten",),
        "sy": ("Syria", "Syrian Arab Republic"),
        "sz": ("Eswatini", "Swaziland"),
        "tc": ("Turks and Caicos Islands",),
        "td": ("Chad",),
        "tf": ("French Southern Territories",),
        "tg": ("Togo",),
        "th": ("Thailand", "ประเทศไทย"),
        "tj": ("Tajikistan",),
        "tk": ("Tokelau",),
        "tl": ("Timor Leste", "East Timor"),
        "tm": ("Turkmenistan",),
        "tn": ("Tunisia",),
        "to": ("Tonga",),
        "tr": ("Turkiye", "Turkey"),
        "tt": ("Trinidad and Tobago",),
        "tv": ("Tuvalu",),
        "tw": ("Taiwan", "Taiwan Province of China"),
        "tz": ("Tanzania", "Tanzania United Republic of"),
        "ua": ("Ukraine",),
        "ug": ("Uganda",),
        "um": ("United States Minor Outlying Islands",),
        "us": ("United States", "United States of America", "US", "USA"),
        "uy": ("Uruguay",),
        "uz": ("Uzbekistan",),
        "va": ("Holy See", "Vatican City"),
        "vc": ("Saint Vincent and the Grenadines", "St Vincent and the Grenadines"),
        "ve": ("Venezuela", "Venezuela Bolivarian Republic of"),
        "vg": ("Virgin Islands British", "British Virgin Islands"),
        "vi": ("Virgin Islands US", "United States Virgin Islands", "US Virgin Islands"),
        "vn": ("Viet Nam", "Vietnam"),
        "vu": ("Vanuatu",),
        "wf": ("Wallis and Futuna",),
        "ws": ("Samoa",),
        "ye": ("Yemen",),
        "yt": ("Mayotte",),
        "za": ("South Africa",),
        "zm": ("Zambia",),
        "zw": ("Zimbabwe",),
    }.items()
    for name in names
}


def country_code_for(
    value: object,
    *,
    extra_aliases: Mapping[str, str] | None = None,
) -> str:
    key = _country_key(value)
    if not key:
        return ""
    if len(key) == 2 and key.isalpha():
        return key
    if extra_aliases:
        extra_code = extra_aliases.get(key)
        if extra_code:
            return extra_code.casefold()
    return COUNTRY_NAME_TO_ALPHA2.get(key, "")


def country_alias_map(
    country_code: object,
    aliases: tuple[str, ...] = (),
) -> dict[str, str]:
    code = country_code_for(country_code)
    if not code:
        code = str(country_code or "").casefold().strip()
    return {_country_key(alias): code for alias in aliases if _country_key(alias)}
